"""Parse Teams transcript files (.vtt and .docx) into structured data."""

import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class TranscriptEntry:
    speaker: str
    text: str
    start_time: str = ""


@dataclass
class Transcript:
    meeting_title: str
    entries: list[TranscriptEntry] = field(default_factory=list)

    @property
    def speakers(self) -> list[str]:
        seen = set()
        return [e.speaker for e in self.entries if e.speaker not in seen and not seen.add(e.speaker)]

    def as_text(self) -> str:
        lines = []
        for entry in self.entries:
            lines.append(f"[{entry.start_time}] {entry.speaker}: {entry.text}")
        return "\n".join(lines)


def parse_vtt(content: str, meeting_title: str = "") -> Transcript:
    """Parse WebVTT transcript generated by Teams."""
    transcript = Transcript(meeting_title=meeting_title)
    blocks = re.split(r"\n\n+", content.strip())

    for block in blocks:
        lines = block.strip().splitlines()
        if not lines or lines[0].startswith("WEBVTT") or lines[0].startswith("NOTE"):
            continue

        time_line = ""
        text_lines = []
        for line in lines:
            if re.match(r"\d{2}:\d{2}:\d{2}", line):
                time_line = line.split("-->")[0].strip()
            elif re.match(r"^\d+$", line):
                continue
            else:
                text_lines.append(line)

        raw_text = " ".join(text_lines).strip()
        if not raw_text:
            continue

        # <v Speaker Name>text  or  Speaker Name: text
        vtt_speaker = re.match(r"<v ([^>]+)>(.*)", raw_text)
        colon_speaker = re.match(r"^([^:]{2,40}):\s+(.*)", raw_text)

        if vtt_speaker:
            speaker = vtt_speaker.group(1).strip()
            text = vtt_speaker.group(2).strip()
        elif colon_speaker:
            speaker = colon_speaker.group(1).strip()
            text = colon_speaker.group(2).strip()
        else:
            speaker = "Inconnu"
            text = raw_text

        if transcript.entries and transcript.entries[-1].speaker == speaker:
            transcript.entries[-1].text += " " + text
        else:
            transcript.entries.append(TranscriptEntry(speaker=speaker, text=text, start_time=time_line))

    return transcript


def parse_docx(file_path: str, meeting_title: str = "") -> Transcript:
    """Parse Teams transcript exported as .docx.

    Teams exports paragraphs like:
        \nSpeaker Name   M:SS\nText line 1\nText line 2
    Each paragraph block starts with a newline then "Name   timestamp".
    """
    from docx import Document

    doc = Document(file_path)
    transcript = Transcript(meeting_title=meeting_title)

    # Teams format: each paragraph text starts with \n then "Speaker   M:SS\ntext"
    for para in doc.paragraphs:
        raw = para.text
        if not raw.strip():
            continue

        # Split on newlines within the paragraph
        lines = [l for l in raw.split("\n") if l.strip()]
        if not lines:
            continue

        # First non-empty line may be "Speaker Name   M:SS"
        header_match = re.match(r"^(.+?)\s{2,}(\d+:\d+)\s*$", lines[0].strip())
        if header_match:
            speaker = header_match.group(1).strip()
            timestamp = header_match.group(2).strip()
            content = " ".join(l.strip() for l in lines[1:] if l.strip())
            if not content:
                continue
            if transcript.entries and transcript.entries[-1].speaker == speaker:
                transcript.entries[-1].text += " " + content
            else:
                transcript.entries.append(TranscriptEntry(speaker=speaker, text=content, start_time=timestamp))
        else:
            # Continuation text without a speaker header
            content = " ".join(l.strip() for l in lines if l.strip())
            if transcript.entries and content:
                transcript.entries[-1].text += " " + content

    return transcript


def parse_file(file_path: str) -> Transcript:
    path = Path(file_path)
    meeting_title = path.stem.replace("_", " ").replace("-", " ")

    if path.suffix.lower() == ".vtt":
        return parse_vtt(path.read_text(encoding="utf-8"), meeting_title)
    elif path.suffix.lower() == ".docx":
        return parse_docx(str(path), meeting_title)
    else:
        raise ValueError(f"Format non supporté : {path.suffix}. Utilisez .vtt ou .docx")
